---
- name: Install kubectl
  dnf:
    name: kubectl
    disable_excludes: kubernetes
    state: present

- name: Pull kubernetes container images
  command: kubeadm config images pull

- name: Initialize kubernetes cluster
  shell: kubeadm init --control-plane-endpoint={{ control_ip }} --pod-network-cidr={{ kubernetes.cidr }} --apiserver-advertise-address {{ ansible_default_ipv4.address }}
  register: output

# - name: Copy output to ansible host
#   copy:
#     dest: /tmp/kube-output.txt
#     content: |-
#       {% for host in ansible_play_hosts_all %}
#       {{ '###' }}{{ host }}{{ '###' }}
#       {{ hostvars[host]['output']['stdout'] }}
#       {% endfor %}
#   delegate_to: localhost

- name: Save output file from master
  copy:
    content: "{{ output.stdout }}"
    dest: /tmp/kube-output.txt

- name: Copy join command to local file
  fetch:
    src: /tmp/kube-output.txt
    dest: /home/ansible/kube-output.txt
    flat: yes

- name: Create .kube directory
  file:
    path: /root/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: "0644"
    remote_src: yes

- name: Fetch file and set permissions
  fetch:
    src: /root/.kube/config
    dest: /home/ansible/kubeconfig.txt
    flat: yes
    validate_checksum: yes
  become_user: root

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: /etc/profile.d/kubeconfig.sh
    line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
    create: yes

- name: Pause for 2 minutes to start kube custer
  pause:
    minutes: 2
