---
- name: Install kubectl
  dnf:
    name: kubectl
    disable_excludes: kubernetes
    state: present

- name: Pull kubernetes container images
  command: kubeadm config images pull

- name: Initialize kubernetes cluster
  shell: kubeadm init --apiserver-advertise-address={{ kubernetes.control_ip }} --pod-network-cidr={{ kubernetes.cidr }} --cri-socket=unix:///run/containerd/containerd.sock
  register: output

- name: Creates kubeconfig directory
  ansible.builtin.file:
    path: /home/{{ user }}/.kube
    state: directory

- name: Creates kubeconfig directory
  ansible.builtin.file:
    path: /root/.kube
    state: directory

- name: Copy kubeconfig file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: "0600"

- name: Copy kubeconfig file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ user }}/.kube/config
    owner: { { user } }
    group: { { user } }
    mode: "0644"

- name: Add kubectl alias
  lineinfile:
    path: /home/{{ user }}/.bashrc
    line: "alias k='kubectl'"
    state: present

- name: Save output file from master
  copy:
    content: "{{ output.stdout }}"
    dest: /tmp/kube-output.txt

- name: Copy join command to local file
  fetch:
    src: /tmp/kube-output.txt
    dest: /home/ansible/kube-output.txt
    flat: yes

- name: Fetch file and set permissions
  fetch:
    src: /home/{{ user }}/.kube/config
    dest: /home/ansible/kubeconfig.txt
    flat: yes
    validate_checksum: yes

- name: Set KUBECONFIG environment variable
  lineinfile:
    path: /etc/profile.d/kubeconfig.sh
    line: "export KUBECONFIG=/home/{{ user }}/.kube/config"
    create: yes

- name: Pause for 2 minutes to start kube custer
  pause:
    minutes: 2
