---
- name: "Apply Nginx controller manifests"
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-{{ ingress_nginx.version }}/deploy/static/provider/{{ ingress_nginx.provider }}/deploy.yaml
    dest: /tmp/ingress_nginx.yaml

- name: Apply Ingress YAML
  command: kubectl apply -f ingress_nginx.yaml
  args:
    chdir: /tmp/

- name: Apply Nginx controller manifests
  get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/{{ metallb.version }}/config/manifests/metallb-native.yaml
    dest: /tmp/metallb.yaml

- name: Apply Ingress YAML
  command: kubectl apply -f metallb.yaml
  args:
    chdir: /tmp/

- name: Pause for MetalLB pods to ready
  shell: kubectl wait pod --all --for=condition=Ready --namespace=metallb-system --timeout=300s

- name: Copy MetalLB IP pool config
  template:
    src: files/metallb-ip.yaml.j2
    dest: /tmp/metallb-ip.yaml

- name: Apply MetalLB IP pool
  command: kubectl apply -f /tmp/metallb-ip.yaml
  args:
    chdir: /tmp/

# For EXT4 and XFS file system
- name: Install Longhorn support package in CentOS
  yum:
    name:
      - iscsi-initiator-utils
      - nfs-utils
    state: present
    update_cache: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Longhorn support package in Ubuntu
  apt:
    name:
      - open-iscsi
      - nfs-common
    state: present
    update_cache: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Start iscsid
  service:
    name: iscsid
    state: started
    enabled: true
